### ISSUE TITLE
Sideloaded App Demo only. I paid for it. 

### ISSUE THREAD

**Issue by iot-resister** [popeen/Popeens-DSub#181]
I'm running it on lineageOS and aurorastore.  Purchased on August 26, 2020. I submitted an issue with the plays store.

https://gitlab.com/AuroraOSS/AuroraStore

**Comment by popeen** [comment]
This will be fixed in the next release. If you have a ticket open with Aurora you can close that, there is nothing they can do about it, it fully my fault. The app will lock down in this way if it wasn't installed by Google Play and it was signed by me. If you build it from source it will not be locked down.

This was an attempt to force people to keep the app up to date but I did not take into account people using third party stores getting this problem and I am not ok with this "feature" causing problems so it will be removed. There should be an update this weekend or next week.

**Comment by jurgenhaas** [comment]
I'm using /e/OS with Aurora too but I have not added a Google account to it as I'd like to keep my phone completely G-free. So I wonder, if I can still pay you for your effort and get the app through Aurora?

**Comment by iot-resister** [comment]
@jurgenhaas trying to fund an alternative 

https://github.com/PaulWoitaschek/Voice/issues/945

**Comment by Friday13th87** [comment]
you can still buy the app via google play webpage and install it trough aurora store afterwards, but you will get the error mentioned (that its a sideloaded "illegal" app version) - if its changed in the next update this should be the way to go - i have the same problem and compiled the app by myself afterwards.
And just for addendum: the modified google play store from nanodroid / microG is not working as well, tried it, same error.

**Comment by jurgenhaas** [comment]
@Friday13th87 when I buy on Google play with account A, but use Aurora without an account, how would that work then?

**Comment by Friday13th87** [comment]
Just buy it at Google play and in aurora you need to login / link with your existing Google account (in the left side menu under accounts)
Afterwards you can install all your existing paid apps in aurora.

**Comment by jurgenhaas** [comment]
Yes, but that way I have to let Google "stuff", even if it's just an account, onto my otherwise Google free mobile phone, which is something I wanted to avoid.

**Comment by Friday13th87** [comment]
Actually no. It's more like checking your Gmail account with an open source browser on your cellphone, nothing else.

Otherwise you can just compile the app by yourself or you can create a android virtual machine on your desktop pc, buy the app there with Google play store and afterwards send the apk to your cellphone, but it's much more complicated.

**Comment by njakes** [comment]
This bug is still happening when using both the standard Aurora Store and the beta.  @popeen has there been an update since the OP started this bug? I am on Calyx OS and have Aurora store and F-droid.  
I would love to be able to use the app.

**Comment by Friday13th87** [comment]
Just use the compiled apk i uploaded.
Here in Github on the upper right go to "Fork" select my fork and you will find the latest version from github compiled. that one will work out for u. Dont know why he is not just using the github version of the app at the play store, then the problem would be solved.
here: https://github.com/Friday13th87/Booksonic-App/releases

**Comment by popeen** [comment]
The "GitHub version" is the same as on the one on play store. It is specifically coded to just show that message if the apk was signed by me and not if it is signed by anyone else. The reasoning behind it at the time was that it was a way to force people to update as I received A LOT of support requests for years old versions. If you compile it yourself that implies that you also recompile the new code before asking for help, that is often not the same if you find an apk online and install that.

What I did not think of was that this would also affect people that keep it updated using third party stores like Aurora.
@njakes @Friday13th87 Thank you for reminding me about it. I will publish a new version to BETA on Google play in a few minutes with this check removed as well as some other new stuff. It can take a day or two before Google approve it

For those interested, fixed in 0310f3eebce22e5dfb43c3ec624a9b15b720bb8b

**Comment by njakes** [comment]
Thank you both for your replies. I am really looking forward to trying your app!

**Comment by popeen** [comment]
New version 2103 fully released and won't limit to demo after sideloading
