### ISSUE TITLE
Include in F-Droid

### ISSUE THREAD

**Issue by miketweaver** [popeen/Popeens-DSub#38]
I would like to request that we work on getting your App added to [F-Droid](https://f-droid.org/), a catalog of FOSS apps for the Android.

The inclusion policy can be found here:
[https://f-droid.org/wiki/page/Inclusion_Policy](https://f-droid.org/wiki/page/Inclusion_Policy)
The how to instructions can be found here:
[https://f-droid.org/wiki/page/Inclusion_How-To](https://f-droid.org/wiki/page/Inclusion_How-To)

**Comment by popeen** [comment]
I might try and do that in the future but not at the moment. 

The problem is that F-Droid builds the app from source instead of me building it and uploading the apk like on for example on google play. It's a great idea in theory since you know the dev isn't adding some fishy code before building but in some cases like this one it causes problems.

While most of the functionality of the app would work some of it wouldn't due to it using APIs that requires keys and I won't add the keys to the repo.

**Comment by miketweaver** [comment]
Do you mind elaborating on the functionality that would be missing if built from source?
I currently am running APK that I built from the repo and haven't found anything missing at all.

**Comment by popeen** [comment]
Sure,

At the moment the APIs that need keys are Pastebin for submitting logs to
me and Boktipset for fetching book descriptions in Swedish if you don't
have it set on the server.

So as long as you don't try and send me a log or have your phone set to
Swedish you will be fine. Should you want to add keys next time you build
they are added here
https://github.com/popeen/Popeens-DSub/blob/master/app/src/main/java/github/popeen/dsub/util/EnvironmentVariables.java

Also if you are building from source you should be aware that the latest
source might not always work that well since I tend to work with only one
branch. Before I release a new version I always make a commit with a
description like "prepare for release" so looking for the latest commit
with that and building from there might be a good idea.

**Comment by SenorSmartyPants** [comment]
I'd love if this could be addressed again. Even without the keys you mention it would be a great addition to F-Droid.

And speaking as a relative git novice switching to working with branches is no big deal at all. Especially if you use a GUI tool like gitkraken.

**Comment by GitJamz** [comment]
Anything new on this subject? I would really like to have booksonic available on fdroid... im sure many more agree..

What can we do to make this happen?

**Comment by GitJamz** [comment]
Please consider this @popeen . F-Droid has grown to become a really big plattform and a lot of people, like me, dont even use google playstore at all for anything.
Most serious trustworthy open source applications are available on F-Droid nowdays. We dont mind that we cant send logs or use other none essential functionality, we are used to it like missing pushnotifications for some stuff etc.. Dont care about it :)

Please consider F-Droid release and we can donate couple pizza and beer for your troubles.
