### ISSUE TITLE
UTF8/ANSI desc.txt & reader.txt

### ISSUE THREAD

**Issue by csy7550** [popeen/Popeens-DSub#54]
Running version 1.1 beta1.

1. Save desc.txt and reader.txt containing norwegian characters 'ÆØÅ' in UTF-8/UTF-8 (BOM) format.

- Web displays ÆØÅ correctly.
- Booksonic android app does NOT.

2. Save desc.txt and reader.txt containing norwegian characters 'ÆØÅ' in ANSI format.

- Web does NOT display 'ÆØÅ' correctly.
- Booksonic android app displays 'ÆØÅ' correctly (!)

Norwegian characters 'ÆØÅ' works fine with titles, etc.

**Comment by Swedie** [comment]
Just started using the Android-app and noticed this is still a problem., same with Swedish special characters ÅÄÖ. 

@popeen Has this been fixed and jut that I'm missing something?

**Comment by popeen** [comment]
@Swedie 
Yes and no,

It wasn't fixed when you commented but I did a test a few minutes ago that solved it. 
If you build from source you can build it from the commit I just pushed. If you get the app from the store it should make it to the next beta (1.0.22-BETA5) that I plan on releasing tomorrow, the full version should be released some time next week as long as no major issues are found.

With this new fix the app can handle both. I don't plan on updating the current server to handle both but the upcoming bridge should be able to use both as well. Would recommend to use UTF8 since that's what the current server can handle.

I will do some more testing and clean up the old code a bit before closing this issue

**EDIT:**
Actually I think I spoke to soon so never mind, I am however working on it

**Comment by Swedie** [comment]
Thanks for the update, I'll wait for the next release :)

**Comment by popeen** [comment]
A new version of the server was released as a pre release a few days ago. In this version special characters work in both app and server as long as the txt files are utf8 encoded.

I will be posting a guide on how to bulk convert all text files in your library to popeen.com sometime this week.
