### ISSUE TITLE
Donate nag

### ISSUE THREAD

**Issue by n8wood** [popeen/Popeens-DSub#59]
Hi, recently I've been getting a message pop up about a 7 day trial and a donation to dsub. I've paid for the app a while back so I'm not sure why I'd be seeing this.

**Comment by popeen** [comment]
Hi,
There are no trials in dsub or Booksonic, however Subsonic has a 30 day trial. It sounds like you are using a Subsonic server without a premium key. 
Once your Subsonic trial runs out you will no longer be able to connect to it with the Booksonic android app, I recommend you download the Booksonic server from http://booksonic.org (its completely free, no premium required) or get a premium key for your Subsonic server.

**Comment by n8wood** [comment]
I don't run Subsonic, I run Madsonic and have been running the same version for quite some time. I'll look into it from that end. Thank you for the reply.

**Comment by popeen** [comment]
Ok, Madsonic also has a premium version however I'm not 100% that premium is required for using android apps on Madsonic so I'm reopening the incident until I can look in to it.

On a side note, you may want to keep an eye out for the next version of the Booksonic server, it will be based of Madsonic instead of Subsonic.

**Comment by n8wood** [comment]
I actually own a premium license for Subsonic, but stopped using it when they dropped the ability to ignore specific directories. Do you know if Booksonic, Libresonic, or some other option has that feature? (sorry if you're annoyed by me asking this in the dsub github page)

**Comment by popeen** [comment]
No problem :)

But I'm afraid I can't answer that. Booksonic is based on the latest Open Source version of Subsonic, unless it was just recently removed from Subsonic it will not be in Booksonic either. As for Libresonic I haven't really kept up to speed with what is going on there.

I'm assuming the functionality is still in Madsonic since you have moved there? If so it will be in the new Booksonic server. If it's not in Madsonic either I'll add it to Booksonic once the new server is ready for release because it sounds like a feature I'm sure a lot of people would like.

**Comment by n8wood** [comment]
Yes, that functionality is in Madsonic. I'll wait for the new release of Booksonic and try that out. Thanks for the help.
